firstname= input("enter first name:")
lastname= input("enter last name:")
print (firstname, lastname)
print (lastname, firstname)
list1=[firstname, lastname]
print (list1)
list1.reverse()
print (list1)
list1.append ("jr")
print (list1)
